// @vitest-environment jsdom
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { afterEach, expect, it } from 'vitest'
import { LeagueComparisonHint, referenceTeamForSave } from './LeagueComparisonHint'
import { referenceFixture } from '../lib/league-reference.fixture'
afterEach(cleanup)
const pair=[{label:'MC / MC',ip:{position:'MC',weights:{passing:5}},oop:{position:'MC',weights:{tackling:5}}}]
const renderHint=(props:Partial<Parameters<typeof LeagueComparisonHint>[0]>={})=>render(<LeagueComparisonHint data={referenceFixture()} team={1} pairs={pair} message="" requestedDate="2034-01-01" sourceDate="2034-01-01" fallback={false} {...props}><button>i</button></LeagueComparisonHint>)

it('opens a compact current/lower/world comparison and closes on Escape',async()=>{renderHint();const b=screen.getByRole('button');fireEvent.focus(b);expect(screen.getByRole('tooltip').id).toBe(b.getAttribute('aria-describedby'));expect(screen.getByText('Sua liga')).toBeTruthy();expect(screen.getByText('Divisão inferior')).toBeTruthy();expect(screen.getByText('Referência mundial')).toBeTruthy();expect(screen.getByText('Checkpoint 01/01/2034')).toBeTruthy();expect(screen.getAllByText('Média').length).toBeGreaterThan(0);expect(screen.getAllByText(/Mediana/).length).toBeGreaterThan(0);expect(screen.getAllByText(/Amostra/).length).toBeGreaterThan(0);expect(screen.getAllByText('Melhor jogador').length).toBe(3);expect(screen.getByText('Jogador 2')).toBeTruthy();expect(screen.getAllByText('Jogador 8').length).toBe(2);expect(screen.queryByText(/25–75%/i)).toBeNull();expect(screen.queryByText(/Amostra parcial do próprio save/i)).toBeNull();fireEvent.keyDown(window,{key:'Escape'});await waitFor(()=>expect(screen.queryByRole('tooltip')).toBeNull())})
it('shows only the checkpoint actually used when fallback selects an earlier reference',()=>{renderHint({requestedDate:'2034-07-01',sourceDate:'2034-01-01',fallback:true});fireEvent.focus(screen.getByRole('button'));expect(screen.getByText('Checkpoint 01/01/2034')).toBeTruthy();expect(screen.queryByText(/01\/07\/2034/)).toBeNull();expect(screen.queryByText(/Referência anterior/i)).toBeNull();expect(screen.getByRole('tooltip').getAttribute('data-reference-fallback')).toBe('true')})
it('keeps a completed season visually simple instead of adding status copy',()=>{const d=referenceFixture();d.checkpoint='2035-01-01';d.cohorts[0].status='historical';d.cohorts[0].reason='same_save_calendar_and_history_completed';renderHint({data:d,requestedDate:'2035-01-01',sourceDate:'2035-01-01'});fireEvent.focus(screen.getByRole('button'));expect(screen.getByText('Checkpoint 01/01/2035')).toBeTruthy();expect(screen.getByText('Sua liga')).toBeTruthy();expect(screen.queryByText(/Temporada encerrada/i)).toBeNull()})
it('shows unavailable data with a short message when no checkpoint can be used',()=>{render(<LeagueComparisonHint data={null} team={null} pairs={[]} message="Nenhuma referência utilizável" requestedDate="2035-01-01" sourceDate={null} fallback={false}><button>i</button></LeagueComparisonHint>);fireEvent.mouseEnter(screen.getByRole('button'));expect(screen.getByText('Nenhuma referência utilizável')).toBeTruthy()})
it('uses the sole human team automatically and fails closed for multiplayer',()=>{const d=referenceFixture();expect(referenceTeamForSave(d)).toBe(1);d.humanTeams.push({team:99,name:'Outra equipe'});expect(referenceTeamForSave(d)).toBeNull();d.humanTeams=[];expect(referenceTeamForSave(d)).toBeNull()})
it('keeps multiplayer messaging short and never asks for manual reference selection',()=>{const d=referenceFixture();d.humanTeams.push({team:99,name:'Outra equipe'});render(<LeagueComparisonHint data={d} team={null} pairs={[]} message="" requestedDate="2034-01-01" sourceDate="2034-01-01" fallback={false}><button>i</button></LeagueComparisonHint>);fireEvent.focus(screen.getByRole('button'));expect(screen.getByText(/saves multiplayer/i)).toBeTruthy();expect(screen.queryByText(/Selecione a equipe de referência/i)).toBeNull()})
