create extension if not exists pgcrypto;

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, display_name text, created_at timestamptz not null default now());
create table public.saves (id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id) on delete cascade, name text not null, club_name text not null, country text, game_version text, save_type text not null default 'unknown' check (save_type in ('youth_only','normal','custom','unknown')), current_season text, notes text, is_archived boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.imports (id uuid primary key default gen_random_uuid(), save_id uuid not null references public.saves(id) on delete cascade, owner_id uuid not null references auth.users(id) on delete cascade, original_filename text not null, file_type text not null check (file_type in ('squad','stats','intake','unknown')), snapshot_date date not null, file_hash text not null, row_count integer not null check (row_count >= 0), detected_encoding text, delimiter text, parser_profile text, source_schema jsonb not null default '{}'::jsonb, warnings jsonb not null default '[]'::jsonb, status text not null default 'uploaded' check (status in ('uploaded','parsed','needs_mapping','imported','failed','duplicate')), created_at timestamptz not null default now(), unique(save_id,file_hash));
create table public.players (id uuid primary key default gen_random_uuid(), save_id uuid not null references public.saves(id) on delete cascade, owner_id uuid not null references auth.users(id) on delete cascade, fm_player_id text, identity_key text not null, current_name text not null, normalized_name text not null, date_of_birth date, nationality text, original_first_seen_name text not null, first_seen_date date not null, last_seen_date date not null, is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(save_id,identity_key));
create table public.player_snapshots (id uuid primary key default gen_random_uuid(), player_id uuid not null references public.players(id) on delete cascade, save_id uuid not null references public.saves(id) on delete cascade, import_id uuid not null references public.imports(id) on delete cascade, snapshot_date date not null, age numeric, club text, squad text, team_level text not null default 'unknown', positions jsonb not null default '[]'::jsonb, preferred_foot text, height numeric, weight numeric, contract_expiry date, wage numeric, transfer_status text, squad_status text, raw_data jsonb not null default '{}'::jsonb, normalized_data jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), unique(player_id,import_id));
create table public.player_attributes (id uuid primary key default gen_random_uuid(), player_snapshot_id uuid not null references public.player_snapshots(id) on delete cascade, attribute_key text not null, attribute_label text not null, value numeric check (value between 1 and 20), source_column text not null, category text not null check (category in ('technical','mental','physical','goalkeeping','hidden_or_other')), created_at timestamptz not null default now(), unique(player_snapshot_id,attribute_key));
create table public.player_stats (id uuid primary key default gen_random_uuid(), player_id uuid not null references public.players(id) on delete cascade, save_id uuid not null references public.saves(id) on delete cascade, import_id uuid not null references public.imports(id) on delete cascade, snapshot_date date not null, season text, competition text, team text, minutes numeric, appearances numeric, starts numeric, sub_appearances numeric, raw_stats jsonb not null default '{}'::jsonb, normalized_stats jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table public.role_models (id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id) on delete cascade, save_id uuid references public.saves(id) on delete cascade, name text not null, position_group text not null, description text, attribute_weights jsonb not null default '{}'::jsonb, stat_weights jsonb not null default '{}'::jsonb, version text not null, is_default boolean not null default false, is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.scoring_models (id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id) on delete cascade, save_id uuid references public.saves(id) on delete cascade, name text not null, version text not null, config jsonb not null, is_active boolean not null default true, created_at timestamptz not null default now());
create table public.player_scores (id uuid primary key default gen_random_uuid(), player_id uuid not null references public.players(id) on delete cascade, snapshot_date date not null, role_model_id uuid references public.role_models(id) on delete set null, scoring_model_id uuid not null references public.scoring_models(id), score_type text not null check (score_type in ('current','role','performance','development','project')), score numeric not null check (score between 0 and 100), attribute_score numeric check (attribute_score between 0 and 100), performance_score numeric check (performance_score between 0 and 100), development_score numeric check (development_score between 0 and 100), confidence numeric not null check (confidence between 0 and 1), explanation jsonb not null, created_at timestamptz not null default now());
create table public.decisions (id uuid primary key default gen_random_uuid(), save_id uuid not null references public.saves(id) on delete cascade, player_id uuid references public.players(id) on delete cascade, owner_id uuid not null references auth.users(id) on delete cascade, decision_date date not null, category text not null, status text, text text not null, season text, created_at timestamptz not null default now());
create table public.import_column_mappings (id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id) on delete cascade, parser_profile text not null, original_column text not null, normalized_key text not null, data_type text not null, category text, ignored boolean not null default false, created_at timestamptz not null default now());

create index players_save_idx on public.players(save_id); create index snapshots_player_date_idx on public.player_snapshots(player_id,snapshot_date); create index stats_player_date_idx on public.player_stats(player_id,snapshot_date);

alter table public.profiles enable row level security; alter table public.saves enable row level security; alter table public.imports enable row level security; alter table public.players enable row level security; alter table public.player_snapshots enable row level security; alter table public.player_attributes enable row level security; alter table public.player_stats enable row level security; alter table public.role_models enable row level security; alter table public.scoring_models enable row level security; alter table public.player_scores enable row level security; alter table public.decisions enable row level security; alter table public.import_column_mappings enable row level security;

create policy profiles_owner on public.profiles for all using (id=auth.uid()) with check (id=auth.uid());
create policy saves_owner on public.saves for all using (owner_id=auth.uid()) with check (owner_id=auth.uid());
create policy imports_owner on public.imports for all using (owner_id=auth.uid()) with check (owner_id=auth.uid());
create policy players_owner on public.players for all using (owner_id=auth.uid()) with check (owner_id=auth.uid());
create policy snapshots_owner on public.player_snapshots for all using (exists(select 1 from public.saves s where s.id=save_id and s.owner_id=auth.uid())) with check (exists(select 1 from public.saves s where s.id=save_id and s.owner_id=auth.uid()));
create policy attributes_owner on public.player_attributes for all using (exists(select 1 from public.player_snapshots ps join public.saves s on s.id=ps.save_id where ps.id=player_snapshot_id and s.owner_id=auth.uid())) with check (exists(select 1 from public.player_snapshots ps join public.saves s on s.id=ps.save_id where ps.id=player_snapshot_id and s.owner_id=auth.uid()));
create policy stats_owner on public.player_stats for all using (exists(select 1 from public.saves s where s.id=save_id and s.owner_id=auth.uid())) with check (exists(select 1 from public.saves s where s.id=save_id and s.owner_id=auth.uid()));
create policy roles_owner on public.role_models for all using (owner_id=auth.uid()) with check (owner_id=auth.uid()); create policy models_owner on public.scoring_models for all using (owner_id=auth.uid()) with check (owner_id=auth.uid());
create policy scores_owner on public.player_scores for all using (exists(select 1 from public.players p where p.id=player_id and p.owner_id=auth.uid())) with check (exists(select 1 from public.players p where p.id=player_id and p.owner_id=auth.uid()));
create policy decisions_owner on public.decisions for all using (owner_id=auth.uid()) with check (owner_id=auth.uid()); create policy mappings_owner on public.import_column_mappings for all using (owner_id=auth.uid()) with check (owner_id=auth.uid());

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,display_name) values(new.id,coalesce(new.raw_user_meta_data->>'display_name',split_part(new.email,'@',1))); return new; end $$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
