import{useEffect,useMemo,useRef,useState,type DragEvent}from'react'
import{useNavigate}from'react-router-dom'
import{supabase}from'../lib/supabase'
import{positionFamilies,positionFamily}from'../lib/reference'
import{PITCH_NODES}from'../lib/tactics'
import{useSaves}from'../features/saves/SaveContext'

type Attribute={attribute_key:string;attribute_label:string;value:number}
type Snapshot={snapshot_date:string;age:number|null;positions:string[];club:string|null;squad:string|null;player_attributes:Attribute[]}
type Player={id:string;current_name:string;nationality:string|null;player_snapshots:Snapshot[]}
type Group={id:string;name:string}
type Planning={groups:Group[];assignments:Record<string,string>;slotAssignments:Record<string,Record<string,string[]>>}
type Assignment={playerId:string;nodeId:string;position:string;roleCode:string;roleName:string}
type Tactic={id:string;name:string;ipAssignments:Assignment[];oopAssignments:Assignment[];lineup:Record<string,string|null>}
type Config=Record<string,unknown>&{planning?:Planning;tactics?:Tactic[];selected_tactic_id?:string|null}
type DragItem={type:'player'|'group';id:string}
const defaults=():Planning=>({groups:[{id:'principal',name:'Principal'},{id:'b',name:'Time B'},{id:'base',name:'Base'}],assignments:{},slotAssignments:{}})

export function PlanningPage(){
  const{selected}=useSaves(),navigate=useNavigate(),[players,setPlayers]=useState<Player[]>([]),[modelId,setModelId]=useState<string|null>(null),[config,setConfig]=useState<Config>({planning:defaults()}),[newGroup,setNewGroup]=useState(''),[search,setSearch]=useState(''),[positionFilter,setPositionFilter]=useState(''),[status,setStatus]=useState('Carregando…'),[dragging,setDragging]=useState<DragItem|null>(null),[quickPlayer,setQuickPlayer]=useState<string|null>(null),[phase,setPhase]=useState<'IP'|'OOP'>('IP'),loaded=useRef(false)
  useEffect(()=>{loaded.current=false;if(!supabase||!selected)return;void Promise.all([supabase.from('players').select('id,current_name,nationality,player_snapshots(snapshot_date,age,positions,club,squad,player_attributes(attribute_key,attribute_label,value))').eq('save_id',selected.id).eq('is_active',true).order('current_name'),supabase.from('scoring_models').select('id,config').eq('save_id',selected.id).eq('name','Model Lab').order('created_at').limit(1).maybeSingle()]).then(([playerResult,modelResult])=>{setPlayers((playerResult.data??[])as unknown as Player[]);const existing=(modelResult.data?.config??{})as Config,old=existing.planning;setConfig({...existing,planning:old?{...defaults(),...old,slotAssignments:old.slotAssignments??{}}:defaults()});setModelId(modelResult.data?.id??null);loaded.current=true;setStatus('Salvo automaticamente')})},[selected?.id])
  useEffect(()=>{if(!loaded.current||!selected||!supabase)return;setStatus('Salvando…');const timer=setTimeout(async()=>{const{data:{user}}=await supabase!.auth.getUser(),payload={owner_id:user!.id,save_id:selected.id,name:'Model Lab',version:'2.6.0',config,is_active:true},result=modelId?await supabase!.from('scoring_models').update(payload).eq('id',modelId).select('id').single():await supabase!.from('scoring_models').insert(payload).select('id').single();if(result.data?.id)setModelId(result.data.id);setStatus(result.error?`Erro: ${result.error.message}`:'Salvo automaticamente')},450);return()=>clearTimeout(timer)},[config,modelId,selected?.id])
  const planning=config.planning??defaults(),tactics=config.tactics??[],tactic=tactics.find(item=>item.id===config.selected_tactic_id)??tactics[0],slots=tactic?(phase==='IP'?tactic.ipAssignments:tactic.oopAssignments):[]
  const latest=(player:Player)=>[...player.player_snapshots].sort((a,b)=>b.snapshot_date.localeCompare(a.snapshot_date))[0]
  const roster=useMemo(()=>players.filter(player=>player.current_name.toLowerCase().includes(search.toLowerCase())&&(!positionFilter||positionFamilies(latest(player)?.positions??[]).includes(positionFilter))).sort((a,b)=>Number(Boolean(planning.assignments[a.id]))-Number(Boolean(planning.assignments[b.id]))||a.current_name.localeCompare(b.current_name,'pt-BR')),[players,search,positionFilter,planning.assignments])
  function updatePlanning(transform:(planning:Planning)=>Planning){setConfig(current=>({...current,planning:transform(current.planning??defaults())}))}
  function assign(playerId:string,groupId:string){updatePlanning(current=>({...current,assignments:{...current.assignments,[playerId]:groupId}}))}
  function addGroup(){const name=newGroup.trim();if(!name)return;updatePlanning(current=>({...current,groups:[...current.groups,{id:crypto.randomUUID(),name}]}));setNewGroup('')}
  function rename(id:string,name:string){updatePlanning(current=>({...current,groups:current.groups.map(group=>group.id===id?{...group,name}:group)}))}
  function remove(id:string){if(!confirm('Excluir este elenco? Os jogadores voltarão para Elenco.'))return;updatePlanning(current=>({groups:current.groups.filter(group=>group.id!==id),assignments:Object.fromEntries(Object.entries(current.assignments).filter(([,groupId])=>groupId!==id)),slotAssignments:Object.fromEntries(Object.entries(current.slotAssignments).filter(([groupId])=>groupId!==id))}))}
  function reorder(targetId:string){if(dragging?.type!=='group'||dragging.id===targetId)return;updatePlanning(current=>{const source=current.groups.find(group=>group.id===dragging.id),without=current.groups.filter(group=>group.id!==dragging.id),index=without.findIndex(group=>group.id===targetId);return source?{...current,groups:[...without.slice(0,index),source,...without.slice(index)]}:current});setDragging(null)}
  function pinPlayer(groupId:string,slotId:string,playerId:string){updatePlanning(current=>{const groupSlots=current.slotAssignments[groupId]??{},currentPlayers=groupSlots[slotId]??[];return{...current,assignments:{...current.assignments,[playerId]:groupId},slotAssignments:{...current.slotAssignments,[groupId]:{...groupSlots,[slotId]:currentPlayers.includes(playerId)?currentPlayers:[...currentPlayers,playerId]}}}})}
  function togglePin(groupId:string,slotId:string,playerId:string){updatePlanning(current=>{const groupSlots=current.slotAssignments[groupId]??{},currentPlayers=groupSlots[slotId]??[],next=currentPlayers.includes(playerId)?currentPlayers.filter(id=>id!==playerId):[...currentPlayers,playerId];return{...current,slotAssignments:{...current.slotAssignments,[groupId]:{...groupSlots,[slotId]:next}}}})}
  function setTactic(id:string){setConfig(current=>({...current,selected_tactic_id:id}))}
  const inspected=players.find(player=>player.id===quickPlayer),inspectedSnapshot=inspected?latest(inspected):undefined
  return <div className="screen-page planning-page"><div className="title-row"><div><h1>Planejamento</h1></div><div className="planning-header-actions"><span className="save-state">{status}</span><input placeholder="Novo elenco" value={newGroup} onChange={event=>setNewGroup(event.target.value)} onKeyDown={event=>{if(event.key==='Enter')addGroup()}}/><button onClick={addGroup}>+ Adicionar</button></div></div>
    <section className="planning-matrix-toolbar"><select value={tactic?.id??''} onChange={event=>setTactic(event.target.value)}><option value="">Selecione uma tática</option>{tactics.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select><div className="phase-compact"><button className={phase==='IP'?'active':''} onClick={()=>setPhase('IP')}>IP</button><button className={phase==='OOP'?'active':''} onClick={()=>setPhase('OOP')}>OOP</button></div><p>Cada jogador aparece em todas as posições compatíveis, mas conta apenas uma vez na cobertura simultânea.</p></section>
    <section className="planning-depth-layout"><article className="planning-column roster-column" onDragOver={event=>event.preventDefault()} onDrop={event=>{event.preventDefault();if(dragging?.type==='player')assign(dragging.id,'');setDragging(null)}}><header><h2>Elenco</h2><span>{players.length}</span></header><div className="roster-filters"><input placeholder="Buscar" value={search} onChange={event=>setSearch(event.target.value)}/><select value={positionFilter} onChange={event=>setPositionFilter(event.target.value)}><option value="">Todas as posições</option>{['GK','D','WB','DM','M','AM','ST'].map(line=><option value={line} key={line}>{line}</option>)}</select></div><div className="planning-player-list">{roster.map(player=><PlayerCard player={player} snapshot={latest(player)} disabled={Boolean(planning.assignments[player.id])} draggable={!planning.assignments[player.id]} onDrag={()=>setDragging({type:'player',id:player.id})} inspect={()=>setQuickPlayer(player.id)} open={()=>navigate(`/players/${player.id}`)} label={planning.groups.find(group=>group.id===planning.assignments[player.id])?.name}/>)}</div></article>
      <div className="depth-matrix-scroll">{tactic?<div className="depth-matrix" style={{gridTemplateColumns:`110px repeat(${planning.groups.length},minmax(230px,1fr))`}}><div className="depth-corner">Posição</div>{planning.groups.map(group=>{const members=players.filter(player=>planning.assignments[player.id]===group.id),coverage=depthCoverage(members,slots,latest);return <div className="depth-group-head" draggable onDragStart={()=>setDragging({type:'group',id:group.id})} onDragOver={event=>event.preventDefault()} onDrop={()=>reorder(group.id)} key={group.id}><span className="drag-handle">⋮⋮</span><input value={group.name} onChange={event=>rename(group.id,event.target.value)}/><button onClick={()=>remove(group.id)}>×</button><small>{coverage.full} camada{coverage.full===1?'':'s'} completa{coverage.full===1?'':'s'} · próxima {coverage.next}/{slots.length}</small></div>})}{slots.map((slot,index)=><DepthRow slot={slot} index={index} groups={planning.groups} players={players} planning={planning} latest={latest} dragging={dragging} startDrag={playerId=>setDragging({type:'player',id:playerId})} drop={(groupId,slotId)=>{if(dragging?.type==='player')pinPlayer(groupId,slotId,dragging.id);setDragging(null)}} togglePin={togglePin} inspect={setQuickPlayer} key={slot.playerId}/>)}</div>:<div className="empty depth-empty"><h2>Crie ou selecione uma tática</h2><p>As posições da formação serão usadas como linhas da matriz de profundidade.</p></div>}</div>
    </section>
    {inspected&&inspectedSnapshot&&<aside className="planning-quick-view"><button className="close" onClick={()=>setQuickPlayer(null)}>×</button><h2>{inspected.current_name}</h2><p>{inspectedSnapshot.positions.join(', ')} · {inspectedSnapshot.age??'—'} anos · {inspected.nationality??'—'}</p><div>{[...inspectedSnapshot.player_attributes].sort((a,b)=>b.value-a.value).slice(0,12).map(attribute=><span key={attribute.attribute_key}>{attribute.attribute_label}<b>{attribute.value}</b></span>)}</div><button onClick={()=>navigate(`/players/${inspected.id}`)}>Abrir ficha completa</button></aside>}
  </div>
}

function DepthRow({slot,index,groups,players,planning,latest,dragging,startDrag,drop,togglePin,inspect}:{slot:Assignment;index:number;groups:Group[];players:Player[];planning:Planning;latest:(player:Player)=>Snapshot|undefined;dragging:DragItem|null;startDrag:(id:string)=>void;drop:(groupId:string,slotId:string)=>void;togglePin:(groupId:string,slotId:string,playerId:string)=>void;inspect:(id:string)=>void}){const label=slotLabel(slot,index);return <><div className="depth-position"><b>{label}</b><span>{slot.roleCode}</span></div>{groups.map(group=>{const members=players.filter(player=>planning.assignments[player.id]===group.id&&canPlay(latest(player)?.positions??[],slot.position)),pinned=planning.slotAssignments[group.id]?.[slot.playerId]??[],ordered=[...members].sort((a,b)=>Number(pinned.includes(b.id))-Number(pinned.includes(a.id))||a.current_name.localeCompare(b.current_name,'pt-BR'));return <div className={`depth-cell ${dragging?.type==='player'?'drop-ready':''}`} onDragOver={event=>event.preventDefault()} onDrop={()=>drop(group.id,slot.playerId)} key={group.id}>{ordered.map(player=><button className={`depth-player-chip ${pinned.includes(player.id)?'pinned':''}`} draggable onDragStart={event=>{event.stopPropagation();startDrag(player.id)}} onClick={()=>togglePin(group.id,slot.playerId,player.id)} onDoubleClick={()=>inspect(player.id)} title="Clique para fixar nesta posição; duplo clique para ver os dados" key={player.id}>{player.current_name}{positionFamilies(latest(player)?.positions??[]).length>1&&<i>↔</i>}</button>)}{!ordered.length&&<span className="depth-missing">Sem opção</span>}</div>})}</>}
function slotLabel(slot:Assignment,index:number){const node=PITCH_NODES.find(item=>item.id===slot.nodeId),lane=node?(node.x<40?'L':node.x>60?'R':'C'):String(index+1);return `${slot.position} ${lane}`}
function canPlay(positions:string[],target:string){const family=positionFamily(target),side=target.match(/\(([^)]+)\)/)?.[1]?.toUpperCase();if(!positionFamilies(positions).includes(family))return false;if(!side)return true;const relevant=positions.filter(position=>new RegExp(`(^|[/,]\\s*)${family}(?=\\s|[/,(]|$)`,'i').test(position));return relevant.some(position=>{const available=position.match(/\(([^)]+)\)/)?.[1]?.toUpperCase();return!available||[...side].some(letter=>available.includes(letter))})}
function maximumMatching(players:Player[],slots:Assignment[],latest:(player:Player)=>Snapshot|undefined,layers:number){const expanded=Array.from({length:layers},()=>slots).flat(),matchedPlayer=new Map<string,number>();function visit(slotIndex:number,seen:Set<string>):boolean{for(const player of players){if(seen.has(player.id)||!canPlay(latest(player)?.positions??[],expanded[slotIndex].position))continue;seen.add(player.id);const previous=matchedPlayer.get(player.id);if(previous===undefined||visit(previous,seen)){matchedPlayer.set(player.id,slotIndex);return true}}return false}let matched=0;for(let index=0;index<expanded.length;index++)if(visit(index,new Set()))matched++;return matched}
function depthCoverage(players:Player[],slots:Assignment[],latest:(player:Player)=>Snapshot|undefined){if(!slots.length)return{full:0,next:0};let full=0;for(let layers=1;layers<=3;layers++){if(maximumMatching(players,slots,latest,layers)===slots.length*layers)full=layers;else break}const nextLayers=full+1,next=Math.max(0,maximumMatching(players,slots,latest,nextLayers)-full*slots.length);return{full,next}}
function PlayerCard({player,snapshot,disabled=false,draggable=false,onDrag,inspect,open,label}:{player:Player;snapshot:Snapshot|undefined;disabled?:boolean;draggable?:boolean;onDrag:()=>void;inspect:()=>void;open:()=>void;label?:string}){return <div className={`planning-player ${disabled?'disabled':''}`} draggable={draggable} onDragStart={event=>{event.stopPropagation();onDrag()}}><div><strong>{player.current_name}</strong><span>{snapshot?.positions?.join(', ')||'Sem posição'} · {snapshot?.age??'—'} anos{label?` · ${label}`:''}</span></div><div className="planning-player-actions"><button onClick={inspect}>Dados</button><button onClick={open}>Abrir</button></div></div>}
