import{useEffect,useMemo,useRef,useState,type MouseEvent as ReactMouseEvent}from'react'
import{createPortal}from'react-dom'
import{useNavigate}from'react-router-dom'
import{supabase}from'../lib/supabase'
import{attributeScore,combinedPhaseScore}from'../lib/scoring'
import{ScoreBadge}from'../components/ScoreBadge'
import{percentile,referenceScore,type ReferenceDataset}from'../lib/reference'
import{roleDefaultWeights}from'../lib/roleWeights'
import{ATTRIBUTE_LOOKUP}from'../lib/attributes'
import{canPlayPosition}from'../lib/positions'
import{loadPlayers,loadReferenceDataset}from'../lib/dataCache'
import{useSaves}from'../features/saves/SaveContext'
type Attribute={attribute_key:string;attribute_label:string;value:number;category:string};type Snapshot={snapshot_date:string;age:number|null;positions:string[];club:string|null;squad:string|null;preferred_foot:string|null;height:number|null;weight:number|null;player_attributes:Attribute[]};type Player={id:string;current_name:string;nationality:string|null;player_snapshots:Snapshot[]};type Group={id:string;name:string};type Planning={groups:Group[];assignments:Record<string,string>;slotAssignments:Record<string,Record<string,string[]>>};type Assignment={playerId:string;nodeId:string;position:string;roleId?:string;roleCode:string;roleName:string};type Pair={ip:Assignment;oop:Assignment};type Tactic={id:string;name:string;ipAssignments:Assignment[];oopAssignments:Assignment[];roles?:{id:string;name:string;weights:Record<string,number>}[]};type Config=Record<string,unknown>&{planning?:Planning;tactics?:Tactic[];selected_tactic_id?:string|null;role_weight_overrides?:Record<string,Record<string,number>>};type DragItem={type:'player';id:string};type SlotSelection={groupId:string;slotId:string;cellIndex:number};type Menu={x:number;y:number;playerId:string;groupId:string;slotId:string;primary:boolean}
type ScoreEntry={id:string;ipPosition:string;ipRole:string;oopPosition:string;oopRole:string;value:number|null;rank:number|null}
const defaults=():Planning=>({groups:[{id:'principal',name:'Principal'},{id:'b',name:'Time B'},{id:'base',name:'Base'}],assignments:{},slotAssignments:{}})
export function PlanningPage(){
 const{selected}=useSaves(),navigate=useNavigate(),[players,setPlayers]=useState<Player[]>([]),[reference,setReference]=useState<ReferenceDataset|null>(null),[modelId,setModelId]=useState<string|null>(null),[config,setConfig]=useState<Config>({planning:defaults()}),[undoPlanning,setUndoPlanning]=useState<Planning|null>(null),[status,setStatus]=useState('Carregando…'),[search,setSearch]=useState(''),[positionFilters,setPositionFilters]=useState<string[]>([]),[dragging,setDragging]=useState<DragItem|null>(null),[selectedGroup,setSelectedGroup]=useState('principal'),[hoverGroup,setHoverGroup]=useState<string|null>(null),[manageOpen,setManageOpen]=useState(false),[newGroup,setNewGroup]=useState(''),[menu,setMenu]=useState<Menu|null>(null),loaded=useRef(false)
 useEffect(()=>{void loadReferenceDataset().then(setReference)},[])
 useEffect(()=>{loaded.current=false;setUndoPlanning(null);if(!supabase||!selected)return;setStatus('Carregando…');void Promise.all([loadPlayers(selected.id),supabase.from('scoring_models').select('id,config').eq('save_id',selected.id).eq('name','Model Lab').order('created_at').limit(1).maybeSingle()]).then(([cached,mr])=>{setPlayers(cached.filter(player=>player.is_active)as unknown as Player[]);const existing=(mr.data?.config??{})as Config,old=existing.planning,base=old?{...defaults(),...old,slotAssignments:old.slotAssignments??{}}:defaults(),placed=Object.fromEntries(Object.entries(base.slotAssignments).flatMap(([groupId,rows])=>Object.values(rows).flat().filter(Boolean).map(playerId=>[playerId,groupId]))),next={...base,assignments:placed};setConfig({...existing,planning:next});setSelectedGroup(next.groups[0]?.id??'');setModelId(mr.data?.id??null);loaded.current=true;setStatus('Salvo automaticamente')}).catch(()=>setStatus('Erro ao carregar dados'))},[selected?.id])
 useEffect(()=>{if(!loaded.current||!selected||!supabase)return;setStatus('Salvando…');const timer=setTimeout(async()=>{const{data:{user}}=await supabase!.auth.getUser(),payload={owner_id:user!.id,save_id:selected.id,name:'Model Lab',version:'2.8.0',config,is_active:true},result=modelId?await supabase!.from('scoring_models').update(payload).eq('id',modelId).select('id').single():await supabase!.from('scoring_models').insert(payload).select('id').single();if(result.data?.id)setModelId(result.data.id);setStatus(result.error?`Erro: ${result.error.message}`:'Salvo automaticamente')},450);return()=>clearTimeout(timer)},[config,modelId,selected?.id])
 useEffect(()=>{const close=()=>setMenu(null);window.addEventListener('click',close);return()=>window.removeEventListener('click',close)},[])
 const planning=config.planning??defaults(),tactics=config.tactics??[],tactic=tactics.find(t=>t.id===config.selected_tactic_id)??tactics[0],pairs:Pair[]=useMemo(()=>tactic?tactic.ipAssignments.map(ip=>({ip,oop:tactic.oopAssignments.find(o=>o.playerId===ip.playerId)??ip})):[],[tactic]),latest=(p:Player)=>[...p.player_snapshots].sort((a,b)=>b.snapshot_date.localeCompare(a.snapshot_date))[0]
 function roleScore(player:Player,slot:Assignment){const snap=latest(player),id=slot.roleId??slot.roleCode,weights=config.role_weight_overrides?.[id]??tactic?.roles?.find(r=>r.id===id)?.weights??roleDefaultWeights(id,slot.roleName);return snap?attributeScore(snap.player_attributes.map(a=>({key:a.attribute_key,value:a.value,weight:weights[a.attribute_key]??3}))):null}
 const pairScores=(p:Player,pair:Pair)=>({ip:roleScore(p,pair.ip),oop:roleScore(p,pair.oop)}),pairRating=(p:Player,pair:Pair)=>combinePhaseScores(pairScores(p,pair))
 const referenceRatings=useMemo(()=>new Map(pairs.map(pair=>{const ipId=pair.ip.roleId??pair.ip.roleCode,oopId=pair.oop.roleId??pair.oop.roleCode,ipWeights=config.role_weight_overrides?.[ipId]??tactic?.roles?.find(role=>role.id===ipId)?.weights??roleDefaultWeights(ipId,pair.ip.roleName),oopWeights=config.role_weight_overrides?.[oopId]??tactic?.roles?.find(role=>role.id===oopId)?.weights??roleDefaultWeights(oopId,pair.oop.roleName),ratings=(reference?.players??[]).filter(player=>canPlay([player.p],pair.ip.position)).map(player=>combinedPhaseScore(referenceScore(player,reference!.attributes,ipWeights),referenceScore(player,reference!.attributes,oopWeights))).filter((value):value is number=>value!==null).sort((a,b)=>a-b);return[pair.ip.playerId,ratings]})),[pairs,reference,config,tactic])
 const pairPercentile=(player:Player,pair:Pair)=>{const value=pairRating(player,pair);return value===null?null:percentile(value,referenceRatings.get(pair.ip.playerId)??[])}
 function bestPair(p:Player){const positions=latest(p)?.positions??[],natural=pairs.filter(pair=>canPlay(positions,pair.ip.position)),pool=natural.length?natural:pairs;return pool.reduce<Pair|undefined>((best,pair)=>!best||(pairRating(p,pair)??-1)>(pairRating(p,best)??-1)?pair:best,undefined)}
 const scoreBreakdown=(player:Player):ScoreEntry[]=>pairs.map(pair=>({id:pair.ip.playerId,ipPosition:pair.ip.position,ipRole:pair.ip.roleCode,oopPosition:pair.oop.position,oopRole:pair.oop.roleCode,value:pairRating(player,pair),rank:pairPercentile(player,pair)}))
 const roster=useMemo(()=>players.map(player=>{const selectedPairs=positionFilters.map(id=>pairs.find(pair=>pair.ip.playerId===id)).filter((pair):pair is Pair=>Boolean(pair)),pair=selectedPairs.length?selectedPairs.reduce<Pair|undefined>((best,current)=>!best||(pairRating(player,current)??-1)>(pairRating(player,best)??-1)?current:best,undefined):bestPair(player),score=pair?pairRating(player,pair):null,rank=pair?pairPercentile(player,pair):null,positions=latest(player)?.positions??[],compatible=selectedPairs.length?selectedPairs.some(current=>canPlay(positions,current.ip.position)||canPlay(positions,current.oop.position)):true;return{player,pair,score,rank,compatible,breakdown:scoreBreakdown(player)}}).filter(row=>!planning.assignments[row.player.id]&&row.player.current_name.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>Number(b.compatible)-Number(a.compatible)||(b.score??0)-(a.score??0)||a.player.current_name.localeCompare(b.player.current_name,'pt-BR')),[players,search,positionFilters,pairs,config,referenceRatings,planning.assignments])
 const activePlayer=players.find(p=>p.id===dragging?.id),currentGroupIndex=Math.max(0,planning.groups.findIndex(group=>group.id===selectedGroup)),currentGroup=planning.groups[currentGroupIndex],currentGroups=currentGroup?[currentGroup]:[]
 function update(fn:(p:Planning)=>Planning){const previous=planning,next=fn(previous);if(next===previous)return;setUndoPlanning(previous);setConfig(c=>({...c,planning:next}))}
 function undo(){if(!undoPlanning)return;setConfig(c=>({...c,planning:undoPlanning}));setUndoPlanning(null)}
 function changeGroup(direction:number){if(!planning.groups.length)return;const next=(currentGroupIndex+direction+planning.groups.length)%planning.groups.length;setSelectedGroup(planning.groups[next].id);setHoverGroup(null)}
 function addGroup(){if(!newGroup.trim())return;update(p=>({...p,groups:[...p.groups,{id:crypto.randomUUID(),name:newGroup.trim()}]}));setNewGroup('')};const rename=(id:string,name:string)=>update(p=>({...p,groups:p.groups.map(g=>g.id===id?{...g,name}:g)}))
 function removeGroup(id:string){if(!confirm('Excluir este elenco?'))return;update(p=>({groups:p.groups.filter(g=>g.id!==id),assignments:Object.fromEntries(Object.entries(p.assignments).filter(([,g])=>g!==id)),slotAssignments:Object.fromEntries(Object.entries(p.slotAssignments).filter(([g])=>g!==id))}))}
 function removePlayer(id:string){update(p=>({...p,assignments:{...p.assignments,[id]:''},slotAssignments:Object.fromEntries(Object.entries(p.slotAssignments).map(([g,rows])=>[g,Object.fromEntries(Object.entries(rows).map(([s,ids])=>[s,ids.filter(x=>x!==id)]))]))}))}
 function clearPlanning(){update(p=>({...p,assignments:{},slotAssignments:{}}))}
 function primary(group:string,slot:string,id:string,cellIndex?:number){update(p=>{const cleaned=Object.fromEntries(Object.entries(p.slotAssignments).map(([groupId,rows])=>[groupId,Object.fromEntries(Object.entries(rows).map(([slotId,ids])=>[slotId,ids.map(playerId=>playerId===id?'':playerId)]))])),targetRows=cleaned[group]??{},target=[...(targetRows[slot]??[])];while(target.length<3)target.push('');const destination=cellIndex??target.findIndex(playerId=>!playerId);if(destination<0||destination>2||target[destination])return p;target[destination]=id;return{...p,assignments:{...p.assignments,[id]:group},slotAssignments:{...cleaned,[group]:{...targetRows,[slot]:target}}}})}
 return <div className="screen-page planning-page"><div className="title-row"><h1>Planejamento</h1><div className="planning-header-actions"><span className="save-state">{status}</span></div></div>
 <section className="planning-matrix-toolbar planning-aligned-toolbar"><select value={tactic?.id??''} onChange={e=>setConfig(c=>({...c,selected_tactic_id:e.target.value}))}><option value="">Selecione uma tática</option>{tactics.map(t=><option value={t.id} key={t.id}>{t.name}</option>)}</select><div className="squad-navigation-row"><div className="squad-pagination"><button onClick={()=>changeGroup(-1)} disabled={planning.groups.length<2}>‹</button><strong>{currentGroup?.name??'Nenhum elenco'}</strong><span>{planning.groups.length?`${currentGroupIndex+1} / ${planning.groups.length}`:'0 / 0'}</span><button onClick={()=>changeGroup(1)} disabled={planning.groups.length<2}>›</button></div><button className="ghost clear-planning-button" onClick={clearPlanning} disabled={!Object.values(planning.assignments).some(Boolean)}>Limpar elenco</button><button className="ghost undo-planning-button" onClick={undo} disabled={!undoPlanning} title="Desfazer a última alteração do planejamento">↶ Desfazer</button><button className="ghost manage-squads-button" onClick={()=>setManageOpen(true)}>Gerenciar elencos</button></div></section>
<section className="planning-depth-layout"><article className="planning-column roster-column"><header><h2>Elenco</h2><span>{roster.length}</span></header><div className="roster-filters"><input placeholder="Buscar" value={search} onChange={e=>setSearch(e.target.value)}/><PositionFilterDropdown pairs={pairs} selected={positionFilters} change={setPositionFilters}/></div><div className="planning-player-list">{roster.map(({player,pair,score,rank,compatible,breakdown})=><PlayerCard player={player} snapshot={latest(player)} pair={pair} score={score} rank={rank} breakdown={breakdown} compatible={compatible} drag={()=>setDragging({type:'player',id:player.id})} dragEnd={()=>{setDragging(null);setHoverGroup(null)}} open={()=>navigate(`/players/${player.id}`)} key={player.id}/>)}</div></article>
<div className="depth-matrix-scroll">{tactic?<div className="depth-matrix" style={{gridTemplateColumns:'150px minmax(0,1fr)'}}><div className="depth-corner">Funções IP / OOP</div>{currentGroups.map(g=>{const coverage=depthCoverage(players.filter(p=>planning.assignments[p.id]===g.id),pairs.map(p=>p.ip),latest);return <div className={`depth-group-head ${hoverGroup===g.id?'player-target':''} ${selectedGroup===g.id?'selected-destination':''}`} key={g.id}><strong>{g.name}</strong><small>{coverage.full} camada{coverage.full===1?'':'s'} completa{coverage.full===1?'':'s'} · próxima {coverage.next}/{pairs.length}</small></div>})}{pairs.map((pair,index)=><DepthRowV2 pair={pair} index={index} groups={currentGroups} players={players} planning={planning} latest={latest} activePlayer={activePlayer} setHoverGroup={setHoverGroup} startDrag={id=>setDragging({type:'player',id})} dragEnd={()=>{setDragging(null);setHoverGroup(null)}} drop={(group,slot,cellIndex)=>{if(activePlayer)primary(group,slot,activePlayer.id,cellIndex);setDragging(null);setHoverGroup(null)}} score={player=>({value:pairRating(player,pair),rank:pairPercentile(player,pair)})} breakdown={scoreBreakdown} open={id=>navigate(`/players/${id}`)} context={(e,data)=>{e.preventDefault();e.stopPropagation();setMenu({x:e.clientX,y:e.clientY,...data})}} key={pair.ip.playerId}/>)}</div>:<div className="empty depth-empty"><h2>Crie ou selecione uma tática</h2></div>}</div></section>
 {manageOpen&&<div className="settings-overlay" onClick={()=>setManageOpen(false)}><section className="squad-manager" onClick={e=>e.stopPropagation()}><header><h2>Gerenciar elencos</h2><button className="close" onClick={()=>setManageOpen(false)}>×</button></header><div className="squad-manager-list">{planning.groups.map(g=><div key={g.id}><input value={g.name} onChange={e=>rename(g.id,e.target.value)}/><button className="column-delete" onClick={()=>removeGroup(g.id)}>Excluir</button></div>)}</div><footer><input placeholder="Novo elenco" value={newGroup} onChange={e=>setNewGroup(e.target.value)} onKeyDown={e=>e.key==='Enter'&&addGroup()}/><button onClick={addGroup}>+ Adicionar</button></footer></section></div>}
 {menu&&<div className="planning-context-menu" style={{left:menu.x,top:menu.y}} onClick={e=>e.stopPropagation()}><button onClick={()=>{removePlayer(menu.playerId);setMenu(null)}}>Remover do elenco</button></div>}</div>}

function DepthRow({pair,index,groups,players,planning,latest,activePlayer,selectedPlayer,hoverGroup,setHoverGroup,startDrag,drop,scores,open,select,context}:{pair:Pair;index:number;groups:Group[];players:Player[];planning:Planning;latest:(p:Player)=>Snapshot|undefined;activePlayer?:Player;selectedPlayer:string|null;hoverGroup:string|null;setHoverGroup:(id:string|null)=>void;startDrag:(id:string)=>void;drop:(g:string,s:string)=>void;scores:(p:Player,pair:Pair)=>{ip:number|null;oop:number|null};open:(id:string)=>void;select:(id:string)=>void;context:(e:ReactMouseEvent,data:Omit<Menu,'x'|'y'>)=>void}){const compatible=activePlayer&&(canPlay(latest(activePlayer)?.positions??[],pair.ip.position)||canPlay(latest(activePlayer)?.positions??[],pair.oop.position));return <><div className={`depth-position dual-role ${activePlayer&&compatible?'drag-compatible':''}`}><span><b>{pair.ip.position}</b><em>{pair.ip.roleCode}</em></span><span><b>{pair.oop.position}</b><em>{pair.oop.roleCode}</em></span></div>{groups.map(g=>{const primary=planning.slotAssignments[g.id]?.[pair.ip.playerId]??[],members=players.filter(p=>planning.assignments[p.id]===g.id&&(canPlay(latest(p)?.positions??[],pair.ip.position)||canPlay(latest(p)?.positions??[],pair.oop.position)||primary.includes(p.id))),ordered=[...members].sort((a,b)=>Number(primary.includes(b.id))-Number(primary.includes(a.id))||a.current_name.localeCompare(b.current_name,'pt-BR'));return <div className={`depth-cell ${hoverGroup===g.id?'column-highlight':''} ${activePlayer&&compatible?'compatible-target':'training-target'}`} onDragEnter={()=>activePlayer&&setHoverGroup(g.id)} onDragOver={e=>e.preventDefault()} onDrop={()=>drop(g.id,pair.ip.playerId)} key={g.id}>{ordered.map(p=>{const value=scores(p,pair),isPrimary=primary.includes(p.id),extra=!isPrimary;return <div className={`depth-player-chip ${isPrimary?'primary':'extra'} ${selectedPlayer===p.id?'selected-player':''}`} draggable onDragStart={()=>startDrag(p.id)} onClick={()=>select(p.id)} onContextMenu={e=>context(e,{playerId:p.id,groupId:g.id,slotId:pair.ip.playerId,primary:isPrimary})} key={p.id}><PlayerPeek player={p} snapshot={latest(p)!}/><button className="player-name" onClick={e=>{e.stopPropagation();open(p.id)}}>{p.current_name}</button>{extra&&<i title="Opção extra; a posição primária é outra">E</i>}<span className="dual-score"><b className={scoreClass(value.ip)}>IP {value.ip?.toFixed(1)??'—'}</b><b className={scoreClass(value.oop)}>OOP {value.oop?.toFixed(1)??'—'}</b></span></div>})}{!ordered.length&&<span className="depth-missing">Sem opção</span>}</div>})}</>}
function PlayerCard({player,snapshot,pair,score,rank,breakdown,compatible,drag,dragEnd,open}:{player:Player;snapshot:Snapshot;pair?:Pair;score:number|null;rank:number|null;breakdown:ScoreEntry[];compatible:boolean;drag:()=>void;dragEnd:()=>void;open:()=>void}){return <div className={`planning-player roster-player-card ${!compatible?'incompatible':''}`} draggable onDragStart={drag} onDragEnd={dragEnd}><PlayerPeek player={player} snapshot={snapshot}/><div className="roster-player-main"><button className="player-name" onClick={e=>{e.stopPropagation();open()}}>{player.current_name}</button><span>{snapshot.positions.join(', ')||'Sem posição informada'}</span><small>{snapshot.age??'—'} anos · {snapshot.height?`${snapshot.height} cm`:'Altura —'} · {footLabel(snapshot.preferred_foot)}</small></div><ScoreWithBreakdown value={score} rank={rank} label={pair?pairLabel(pair):'Sem função'} entries={breakdown}/></div>}
function PositionFilterDropdown({pairs,selected,change}:{pairs:Pair[];selected:string[];change:(ids:string[])=>void}){const label=!selected.length?'Todas as posições':selected.length===1?'1 posição selecionada':`${selected.length} posições selecionadas`;return <details className="position-multi-filter"><summary>{label}<span>⌄</span></summary><div className="position-multi-menu"><header><b>Posições da tática</b>{selected.length>0&&<button type="button" onClick={()=>change([])}>Limpar</button>}</header>{pairs.map(pair=>{const checked=selected.includes(pair.ip.playerId);return <label className={`planning-line-${planningLine(pair.ip.position)}`} key={pair.ip.playerId}><input type="checkbox" checked={checked} onChange={event=>change(event.target.checked?[...selected,pair.ip.playerId]:selected.filter(id=>id!==pair.ip.playerId))}/><span><b>{pair.ip.position}</b> {pair.ip.roleCode}</span><i>→</i><span><b>{pair.oop.position}</b> {pair.oop.roleCode}</span></label>})}</div></details>}
function PlayerPeek({player,snapshot}:{player:Player;snapshot:Snapshot}){const[anchor,setAnchor]=useState<{top:number;left:number}|null>(null);return <span className="player-peek-wrap"><button className="player-peek" aria-label="Prévia do jogador" onMouseEnter={()=>setAnchor({left:window.innerWidth/2,top:window.innerHeight/2})} onMouseLeave={()=>setAnchor(null)}>♟</button>{anchor&&createPortal(<PlayerTooltip player={player} snapshot={snapshot} anchor={anchor}/>,document.body)}</span>}
function PlayerTooltip({player,snapshot,anchor}:{player:Player;snapshot:Snapshot;anchor:{top:number;left:number}}){const groups=['technical','mental','physical','goalkeeping'];return <aside className="fm-player-tooltip fm-player-tooltip-portal" style={{top:anchor.top,left:anchor.left}}><header><div className="profile-silhouette">♟</div><div><h2>{player.current_name}</h2><p>{snapshot.positions.join(', ')} · {snapshot.age??'—'} anos</p><small>{snapshot.club??'—'} · {player.nationality??'—'} · {snapshot.height?`${snapshot.height} cm`:'—'} · {footLabel(snapshot.preferred_foot)}</small></div></header><div className="fm-attribute-columns">{groups.map(group=><section key={group}><h3>{{technical:'Técnico',mental:'Mental',physical:'Físico',goalkeeping:'Goleiro'}[group]}</h3>{snapshot.player_attributes.filter(attribute=>(ATTRIBUTE_LOOKUP[attribute.attribute_key]?.category??attribute.category)===group).sort((a,b)=>a.attribute_label.localeCompare(b.attribute_label)).map(attribute=><span key={attribute.attribute_key}>{attribute.attribute_label}<b className={attributeClass(attribute.value)}>{attribute.value}</b></span>)}</section>)}</div></aside>}
const canPlay=canPlayPosition
function planningLine(position:string){const value=position.toUpperCase().replaceAll(' ','');if(value.startsWith('GK'))return'gk';if(value.startsWith('ST'))return'st';if(value.startsWith('AM'))return'am';if(value.startsWith('M'))return'm';if(value.startsWith('DM')||value.startsWith('WB'))return'dm';return'd'}
function maximumMatching(players:Player[],slots:Assignment[],latest:(p:Player)=>Snapshot|undefined,layers:number){const expanded=Array.from({length:layers},()=>slots).flat(),matched=new Map<string,number>();function visit(index:number,seen:Set<string>):boolean{for(const p of players){if(seen.has(p.id)||!canPlay(latest(p)?.positions??[],expanded[index].position))continue;seen.add(p.id);const previous=matched.get(p.id);if(previous===undefined||visit(previous,seen)){matched.set(p.id,index);return true}}return false}let count=0;for(let i=0;i<expanded.length;i++)if(visit(i,new Set()))count++;return count}
function depthCoverage(players:Player[],slots:Assignment[],latest:(p:Player)=>Snapshot|undefined){if(!slots.length)return{full:0,next:0};let full=0;for(let l=1;l<=3;l++){if(maximumMatching(players,slots,latest,l)===slots.length*l)full=l;else break}return{full,next:Math.max(0,maximumMatching(players,slots,latest,full+1)-full*slots.length)}}
const scoreClass=(v:number|null)=>v===null?'score-none':v>=75?'score-high':v>=50?'score-mid':'score-low',attributeClass=(v:number)=>v>=15?'attribute-high':v>=10?'attribute-mid':'attribute-low',footLabel=(foot:string|null)=>foot?`Pé ${foot}`:'Pé —'
function combinePhaseScores({ip,oop}:{ip:number|null;oop:number|null}){return combinedPhaseScore(ip,oop)}
function OverallScore({value,rank}:{value:number|null;rank:number|null}){return <ScoreBadge value={value} rank={rank}/>}
function pairLabel(pair:Pair){return `${pair.ip.position} · ${pair.ip.roleCode}/${pair.oop.roleCode}`}
function ScoreWithBreakdown({value,rank,label,entries}:{value:number|null;rank:number|null;label:string;entries:ScoreEntry[]}){const[anchor,setAnchor]=useState<DOMRect|null>(null),left=anchor?Math.min(Math.max(12,anchor.left+anchor.width/2-170),window.innerWidth-352):0,above=Boolean(anchor&&anchor.top>430),top=anchor?(above?anchor.top-8:anchor.bottom+8):0;return <span className="score-context-wrap" tabIndex={0} onMouseEnter={event=>setAnchor(event.currentTarget.getBoundingClientRect())} onMouseLeave={()=>setAnchor(null)} onFocus={event=>setAnchor(event.currentTarget.getBoundingClientRect())} onBlur={()=>setAnchor(null)}><small className="score-context-label">{label}</small><ScoreBadge value={value} rank={rank}/>{anchor&&createPortal(<aside className={`score-breakdown-tooltip ${above?'above':'below'}`} style={{left,top}}><header><b>Notas na tática atual</b><small>IP e OOP combinados</small></header><div>{entries.map(entry=><span className={pairLabelFromEntry(entry)===label?'active':''} key={entry.id}><i><b>{entry.ipPosition}</b><small>{entry.ipRole}</small></i><em>↔</em><i><b>{entry.oopPosition}</b><small>{entry.oopRole}</small></i><ScoreBadge value={entry.value} rank={entry.rank} className="score-badge-compact"/></span>)}</div></aside>,document.body)}</span>}
function pairLabelFromEntry(entry:ScoreEntry){return `${entry.ipPosition} · ${entry.ipRole}/${entry.oopRole}`}

function DepthRowV2({pair,index,groups,players,planning,latest,activePlayer,setHoverGroup,startDrag,dragEnd,drop,score,breakdown,open,context}:{pair:Pair;index:number;groups:Group[];players:Player[];planning:Planning;latest:(p:Player)=>Snapshot|undefined;activePlayer?:Player;setHoverGroup:(id:string|null)=>void;startDrag:(id:string)=>void;dragEnd:()=>void;drop:(g:string,s:string,i:number)=>void;score:(p:Player)=>{value:number|null;rank:number|null};breakdown:(p:Player)=>ScoreEntry[];open:(id:string)=>void;context:(e:ReactMouseEvent,data:Omit<Menu,'x'|'y'>)=>void}){
 const compatible=activePlayer&&(canPlay(latest(activePlayer)?.positions??[],pair.ip.position)||canPlay(latest(activePlayer)?.positions??[],pair.oop.position))
 return <><div className={`depth-position dual-role ${activePlayer&&compatible?'drag-compatible':''}`}><span className={`planning-line-${planningLine(pair.ip.position)}`}><b>{pair.ip.position}</b><em>{pair.ip.roleCode}</em></span><span className={`planning-line-${planningLine(pair.oop.position)}`}><b>{pair.oop.position}</b><em>{pair.oop.roleCode}</em></span></div>{groups.map(group=>{
  const assignedIds=[...(planning.slotAssignments[group.id]?.[pair.ip.playerId]??[])].slice(0,3);while(assignedIds.length<3)assignedIds.push('');const cells:(Player|null)[]=assignedIds.map(id=>players.find(player=>player.id===id)??null),previewIndex=activePlayer?cells.findIndex(player=>!player):-1
  return <div className={`depth-cell depth-three-slots planning-line-${planningLine(pair.ip.position)} ${activePlayer&&compatible?'compatible-target selected-natural':'training-target'}`} key={group.id}>{cells.map((player,cellIndex)=>player?<DepthPlayer player={player} snapshot={latest(player)!} score={score(player)} label={pairLabel(pair)} breakdown={breakdown(player)} startDrag={()=>startDrag(player.id)} dragEnd={dragEnd} open={()=>open(player.id)} context={event=>context(event,{playerId:player.id,groupId:group.id,slotId:pair.ip.playerId,primary:true})} key={`${player.id}-${cellIndex}`}/>:<div className={`depth-vacancy ${activePlayer&&previewIndex===cellIndex?'preview-vacancy':''}`} onDragEnter={event=>{event.stopPropagation();activePlayer&&setHoverGroup(group.id);event.currentTarget.classList.add('drop-hover')}} onDragLeave={event=>event.currentTarget.classList.remove('drop-hover')} onDragOver={event=>event.preventDefault()} onDrop={event=>{event.preventDefault();event.stopPropagation();event.currentTarget.classList.remove('drop-hover');drop(group.id,pair.ip.playerId,cellIndex)}} aria-label={`Vaga ${cellIndex+1} livre`} key={`vacancy-${cellIndex}`}>{activePlayer&&previewIndex===cellIndex?<PreviewPlayer player={activePlayer} snapshot={latest(activePlayer)!} score={score(activePlayer)}/>:<span>+</span>}</div>)}</div>
 })}</>}
function DepthPlayer({player,snapshot,score,label,breakdown,startDrag,dragEnd,open,context}:{player:Player;snapshot:Snapshot;score:{value:number|null;rank:number|null};label:string;breakdown:ScoreEntry[];startDrag:()=>void;dragEnd:()=>void;open:()=>void;context:(event:ReactMouseEvent)=>void}){return <div className="depth-player-chip primary" draggable onDragStart={startDrag} onDragEnd={dragEnd} onContextMenu={context}><PlayerPeek player={player} snapshot={snapshot}/><div className="matrix-player-info"><button className="player-name" onClick={event=>{event.stopPropagation();open()}}>{player.current_name}</button><small>{snapshot.age??'—'} anos · {snapshot.positions.join(', ')||'Sem posição'}</small></div><ScoreWithBreakdown value={score.value} rank={score.rank} label={label} entries={breakdown}/></div>}
function PreviewPlayer({player,snapshot,score}:{player:Player;snapshot:Snapshot;score:{value:number|null;rank:number|null}}){return <div className="depth-player-chip planning-player-preview"><span className="player-peek">♟</span><div className="matrix-player-info"><strong>{player.current_name}</strong><small>{snapshot.age??'—'} anos · {snapshot.positions.join(', ')||'Sem posição'}</small></div><OverallScore value={score.value} rank={score.rank}/></div>}
