import{useEffect,useMemo,useState}from'react'
import{useNavigate,useParams}from'react-router-dom'
import{supabase}from'../lib/supabase'
import{ATTRIBUTE_CATALOG}from'../lib/attributes'

type Attribute={attribute_key:string;attribute_label:string;value:number;category:string}
type Snapshot={id:string;snapshot_date:string;age:number|null;club:string|null;squad:string|null;positions:string[];preferred_foot?:string|null;height?:number|null;weight?:number|null;contract_expiry:string|null;raw_data:Record<string,unknown>;normalized_data:Record<string,unknown>;player_attributes:Attribute[]}
type Player={id:string;fm_player_id:string|null;current_name:string;nationality:string|null;date_of_birth:string|null;first_seen_date:string;last_seen_date:string;is_active:boolean;player_snapshots:Snapshot[]}
type Stat={id:string;snapshot_date:string;season:string|null;competition:string|null;team:string|null;minutes:number|null;appearances:number|null;starts:number|null;sub_appearances:number|null;raw_stats:Record<string,unknown>;normalized_stats:Record<string,unknown>}

export function PlayerPage(){
  const{id}=useParams(),navigate=useNavigate(),[player,setPlayer]=useState<Player|null>(null),[stats,setStats]=useState<Stat[]>([]),[index,setIndex]=useState(0),[compareMode,setCompareMode]=useState('previous')
  useEffect(()=>{if(!supabase||!id)return;void Promise.all([
    supabase.from('players').select('id,fm_player_id,current_name,nationality,date_of_birth,first_seen_date,last_seen_date,is_active,player_snapshots(id,snapshot_date,age,club,squad,positions,preferred_foot,height,weight,contract_expiry,raw_data,normalized_data,player_attributes(attribute_key,attribute_label,value,category))').eq('id',id).single(),
    supabase.from('player_stats').select('id,snapshot_date,season,competition,team,minutes,appearances,starts,sub_appearances,raw_stats,normalized_stats').eq('player_id',id).order('snapshot_date')
  ]).then(([playerResult,statsResult])=>{const value=playerResult.data as unknown as Player|null;if(value){value.player_snapshots.sort((a,b)=>a.snapshot_date.localeCompare(b.snapshot_date));setPlayer(value);setIndex(Math.max(0,value.player_snapshots.length-1))}setStats((statsResult.data??[])as Stat[])})},[id])
  const snapshots=player?.player_snapshots??[],current=snapshots[index]
  const compareIndex=useMemo(()=>compareMode==='previous'?Math.max(0,index-1):compareMode==='oldest'?0:Number(compareMode),[compareMode,index]),comparison=snapshots[compareIndex]
  if(!player)return <div className="screen-page player-page"><p>Carregando ficha do jogador…</p></div>
  return <div className="screen-page player-page"><div className="title-row"><div><button className="back-button" onClick={()=>window.history.length>1?navigate(-1):navigate('/squad')}>← Voltar</button><h1>{player.current_name}</h1></div><div className="player-snapshot-control"><label>Snapshot <span>{index+1}/{snapshots.length}</span><input type="range" min="0" max={Math.max(0,snapshots.length-1)} value={index} disabled={snapshots.length<=1} onChange={event=>setIndex(Number(event.target.value))}/></label><strong>{current?.snapshot_date??'Sem snapshot'}</strong></div></div>{current?<div className="player-page-body">
    <section className="player-summary-grid"><Info label="Idade" value={current.age}/><Info label="Nacionalidade" value={player.nationality}/><Info label="Nascimento" value={player.date_of_birth}/><Info label="Posições" value={current.positions?.join(', ')}/><Info label="Equipe" value={current.club||current.squad}/><Info label="Pé preferido" value={current.preferred_foot||field(current,'preferred_foot')}/><Info label="Altura" value={current.height?`${current.height} cm`:field(current,'height')}/><Info label="Peso" value={current.weight?`${current.weight} kg`:field(current,'weight')}/><Info label="Contrato" value={current.contract_expiry}/><Info label="ID do FM" value={player.fm_player_id}/></section>
    <section className="card player-attributes-panel"><header><div><span className="eyebrow">ATRIBUTOS</span><h2>{current.snapshot_date}</h2></div><label>Comparar com<select value={compareMode} disabled={snapshots.length<=1} onChange={event=>setCompareMode(event.target.value)}><option value="previous">Snapshot anterior</option><option value="oldest">Primeiro snapshot</option>{snapshots.map((snapshot,snapshotIndex)=><option value={snapshotIndex} key={snapshot.id}>{snapshot.snapshot_date}</option>)}</select></label></header><div className="player-attribute-groups">{(['technical','mental','physical','goalkeeping']as const).map(category=><section key={category}><h3>{{technical:'Técnico',mental:'Mental',physical:'Físico',goalkeeping:'Goleiro'}[category]}</h3>{ATTRIBUTE_CATALOG.filter(attribute=>attribute.category===category).sort((a,b)=>a.label.localeCompare(b.label,'pt-BR')).map(definition=>{const attribute=current.player_attributes.find(item=>item.attribute_key===definition.key),old=comparison?.player_attributes.find(item=>item.attribute_key===definition.key),delta=attribute&&old?attribute.value-old.value:null;return <div className="player-attribute-row" key={definition.key}><span>{attribute?.attribute_label??definition.label}</span><b>{attribute?.value??'—'}</b><small className={delta&&delta>0?'up':delta&&delta<0?'down':''}>{delta===null||delta===0?'':`${delta>0?'+':''}${delta}`}</small></div>})}</section>)}</div></section>
    <section className="player-data-grid"><div className="card"><h2>Dados do snapshot</h2><DataTable data={{...current.raw_data,...current.normalized_data}}/></div><div className="card"><h2>Histórico estatístico</h2>{[...stats].sort((a,b)=>b.snapshot_date.localeCompare(a.snapshot_date)).map(stat=><div className="player-stat-block" key={stat.id}><strong>{stat.snapshot_date} · {stat.competition||stat.season||stat.team||'Estatísticas'}</strong><DataTable data={{minutes:stat.minutes,appearances:stat.appearances,starts:stat.starts,sub_appearances:stat.sub_appearances,...stat.raw_stats,...stat.normalized_stats}}/></div>)}{!stats.length&&<p>Nenhuma importação de estatísticas para este jogador.</p>}</div></section>
  </div>:<p>Este jogador ainda não possui snapshots.</p>}</div>
}
function field(snapshot:Snapshot,key:string){const value=snapshot.normalized_data?.[key]??Object.entries(snapshot.raw_data??{}).find(([label])=>label.toLowerCase().replace(/\W/g,'_').includes(key))?.[1];return value==null?'—':String(value)}
function Info({label,value}:{label:string;value:unknown}){return <div><small>{label}</small><strong>{value==null||value===''?'—':String(value)}</strong></div>}
function DataTable({data}:{data:Record<string,unknown>}){const entries=Object.entries(data).filter(([,value])=>value!==null&&value!==undefined&&String(value).trim()!=='');return entries.length?<div className="player-data-table">{entries.map(([key,value])=><div key={key}><span>{key}</span><strong>{typeof value==='object'?JSON.stringify(value):String(value)}</strong></div>)}</div>:<p>Nenhum dado adicional neste snapshot.</p>}
