import { describe, it, expect } from 'vitest'
import { ATTRIBUTE_CATALOG } from './attributes'
import { currentLeague, leaguePopulation, leagueComparisons, summarizeLeagueGeneralAttributes, summarizeLeagueRole, worldLeagueBenchmark, isLeagueReference, LEAGUE_REFERENCE_VERSION, type LeagueReference } from './league-reference'
import { adjacentLeagues, readLeagueRule, type LeagueRule } from './fm26-league-rules'
import { deriveHeaderLeaguePopulations, readLeagueCalendars, readContractRegistryDiagnostic } from './fm26-league-reader'
import { buildCompetitionIdentityIndex, readCompetitionHistory } from './fm26-competition-history'
import { pairedRoleScore } from './role-scoring'

import { rule, referenceFixture } from './league-reference.fixture'
describe('same-save league references',()=>{
  it('shows current, lower and the strongest available world benchmark without the upper league',()=>{ const d=referenceFixture(), rows=leagueComparisons(d,1).rows;expect(rows.map(r=>[r.direction,r.target,r.population.players.length,r.population.teams])).toEqual([['current',68,2,2],['down',200,4,4],['world',200,4,4]]) })
  it('requires every group; never silently uses only the linked subgroup',()=>{const d=referenceFixture();d.cohorts=d.cohorts.filter(c=>c.uid!==201);expect(leaguePopulation(d,200)).toMatchObject({status:'unknown',missingGroups:[201],players:[]})})
  it('keeps header-only active leagues tentative but preserves the latest corroborated completed edition',()=>{const d=referenceFixture();d.cohorts[0].status='candidate';expect(currentLeague(d,1).status).toBe('candidate');d.cohorts[0].status='historical';d.cohorts[0].reason='same_save_calendar_and_history_completed';d.checkpoint='2035-01-01';expect(currentLeague(d,1)).toMatchObject({status:'confirmed',reason:'latest_completed_league'});expect(leaguePopulation(d,68).status).toBe('available_partial')})
  it('flags recoverable 0.43.0/0.43.1 current references for reprocessing',()=>{const d=referenceFixture();d.cohorts[0].status='unresolved';d.cohorts[0].reason='identity_or_headers_unresolved';expect(currentLeague(d,1)).toMatchObject({status:'unknown',reason:'legacy_reference_needs_refresh'})})
  it('does not let an older completed season override a newer active candidate',()=>{const d=referenceFixture();d.checkpoint='2034-01-01';d.cohorts[0].status='historical';d.cohorts[0].reason='same_save_calendar_and_history_completed';d.cohorts[0].last='2033-12-20';d.cohorts.push({...d.cohorts[0],uid:67,raw:67,kind:999,season:'2034-08-01',last:'2034-08-01',status:'candidate',reason:'header_consensus_only'});expect(currentLeague(d,1)).toMatchObject({status:'candidate',reason:'header_consensus_only'})})
  it('rejects overlapping teams and conflicting identities',()=>{const d=referenceFixture();d.cohorts[3].teams=[5,8];expect(leaguePopulation(d,200).status).toBe('ambiguous');const e=referenceFixture();e.players.push({...e.players[0],birth:'2011-01-01'});expect(leaguePopulation(e,68).reason).toBe('conflicting_identity')})
  it('excludes zero-quota lower adjacency and roots missing an edge',()=>{const d=referenceFixture();d.rules[0].roots[0].edges[1].places=0;expect(leagueComparisons(d,1).rows[1].reason).toBe('quota_not_positive');d.rules[0].roots.push({...d.rules[0].roots[0],edges:[]});expect(adjacentLeagues(68,d.rules)).toEqual([])})
  it('uses canonical paired score, exact numeric positions and explicit missing-attribute exclusions',()=>{const d=referenceFixture(),pop=leaguePopulation(d,68),pair={label:'MC',ip:{position:'MC',weights:{passing:5}},oop:{position:'MC',weights:{tackling:5}}};const s=summarizeLeagueRole(d,pop,pair)!;expect(s.n).toBe(2);expect(s.mean).toBe(pairedRoleScore(d.attributes.map(attribute_key=>({attribute_key,value:10.5})),pair.ip.weights,pair.oop.weights));expect(s.best).toMatchObject({name:'Jogador 2',uid:100001,team:2});expect(s.best?.score).toBeGreaterThan(s.mean!);pop.players[0].attributes[d.attributes.indexOf('passing')]=null;expect(summarizeLeagueRole(d,pop,pair)).toMatchObject({n:1,missing:1,best:{name:'Jogador 2'}});pair.oop.position='DM';expect(summarizeLeagueRole(d,pop,pair)).toMatchObject({n:0,ineligible:2,median:null,best:null})})
  it('selects the world benchmark by equal mean of visible attributes',()=>{const d=referenceFixture(),world=worldLeagueBenchmark(d)!;expect(world.target).toBe(200);expect(world.general.mean).toBe(15.5)})
  it('keeps lower and world populations available from corroborated completed editions',()=>{const d=referenceFixture();d.checkpoint='2035-01-01';d.cohorts.forEach(c=>{c.status='historical';c.reason='same_save_calendar_and_history_completed'});const rows=leagueComparisons(d,1).rows;expect(rows.map(row=>row.direction)).toEqual(['current','down','world']);expect(rows[0].population.status).toBe('available_partial');expect(rows[1].population.status).toBe('available_partial')})
  it('uses a confirmed roster-header population when an adjacent division has no fixture cohort',()=>{const d=referenceFixture();d.cohorts=d.cohorts.filter(c=>![201,202].includes(c.uid ?? -1));d.headerPopulations=[{uid:201,raw:301,teams:[5,6],expectedTeams:2,seasonEndYear:2033,reason:'same_save_roster_headers_and_history_shape'},{uid:202,raw:302,teams:[7,8],expectedTeams:2,seasonEndYear:2033,reason:'same_save_roster_headers_and_history_shape'}];const lower=leaguePopulation(d,200);expect(lower).toMatchObject({status:'available_partial',teams:4,coveredTeams:4});expect(leagueComparisons(d,1).rows[1]).toMatchObject({direction:'down',population:{status:'available_partial'}})})
  it('reports general-attribute coverage without treating missing cells as zero',()=>{const d=referenceFixture(),pop=leaguePopulation(d,68);pop.players[0].attributes[0]=null;const summary=summarizeLeagueGeneralAttributes(d,pop);expect(summary.coverage).toBeLessThan(1);expect(summary.observed).toBe(summary.possible-1);expect(summary.mean).toBeGreaterThan(10)})
  it('does not rank a regional child separately when an aggregate league family exists',()=>{const d=referenceFixture();d.players.filter(player=>[5,6].includes(player.team)).forEach(player=>player.attributes=player.attributes.map(()=>20));const world=worldLeagueBenchmark(d)!;expect(world.target).toBe(200);expect(world.population.teams).toBe(4)})
  it('keeps player names optional for old persisted references while accepting named players',()=>{const d=referenceFixture();expect(isLeagueReference(d)).toBe(true);delete d.players[0].name;expect(isLeagueReference(d)).toBe(true)})
  it('fails closed for malformed persisted payloads without throwing',()=>{expect(isLeagueReference(referenceFixture())).toBe(true);for(const bad of [null,{}, {...referenceFixture(),rules:[null]}, {...referenceFixture(),players:[null]}, {...referenceFixture(),attributes:['current_ability']}])expect(isLeagueReference(bad)).toBe(false)})
})
const put=(b:Uint8Array,p:number,n:number)=>new DataView(b.buffer).setUint32(p,n,true)
const packed=(year:number,day:number)=>(year<<16)|day
function calendar(){const b=new Uint8Array(8*7*40);let p=0;for(let a=1;a<=8;a++)for(let c=1;c<=8;c++){if(a===c)continue;b[p]=0x1c;put(b,p+1,90);put(b,p+12,a);b[p+16]=255;put(b,p+19,c);b[p+23]=255;put(b,p+25,packed(2034,150));put(b,p+29,packed(2034,180));p+=40}return b}
function identities(){const b=new Uint8Array(23);b.set([1,0,0x6c,7,1,0,0x6c,7]);b[10]=255;put(b,11,51);put(b,15,67);put(b,19,67);return buildCompetitionIdentityIndex(b)}
describe('header population evidence boundaries',()=>{
  it('requires an exact same-save league-history team count before promoting roster headers',async()=>{const h=await readCompetitionHistory({});h.seasons.push({season_end_year:2033,competition_id_raw:51,competition_uid:67,competition_identity_status:'confirmed',team_count:8} as never);const headers=new Map(Array.from({length:8},(_,i)=>[i+1,new Set([51])]));expect(deriveHeaderLeaguePopulations(headers,h,identities(),[rule(67,0)])).toEqual([{uid:67,raw:51,teams:[1,2,3,4,5,6,7,8],expectedTeams:8,seasonEndYear:2033,reason:'same_save_roster_headers_and_history_shape'}]);headers.set(9,new Set([51]));expect(deriveHeaderLeaguePopulations(headers,h,identities(),[rule(67,0)])).toEqual([])})
})

describe('calendar evidence boundaries',()=>{
  it('uses unique same-save history mapping while treating extra squad headers as non-conflicting evidence',async()=>{const h=await readCompetitionHistory({}),b=calendar(),headers=new Map(Array.from({length:8},(_,i)=>[i+1,new Set([51])])),r=[rule(67,0)];const run=()=>readLeagueCalendars(b,b.length,h,headers,identities(),r,'2034-01-01');expect(run()[0].status).toBe('candidate');h.seasons.push({fixture_status:'confirmed',fixture_kind_raw:90,competition_id_raw:51} as never);expect(run()[0]).toMatchObject({status:'confirmed',reason:'same_save_calendar_and_history'});headers.get(1)!.add(52);expect(run()[0].status).toBe('confirmed');headers.set(1,new Set([52]));expect(run()[0]).toMatchObject({status:'unresolved',reason:'history_header_conflict'});headers.set(1,new Set([51]));b[0]=0;expect(run()).toEqual([])})
  it('does not borrow a conflicting kind mapping and marks a corroborated completed season as a reusable historical reference',async()=>{const h=await readCompetitionHistory({});h.seasons.push({fixture_status:'confirmed',fixture_kind_raw:90,competition_id_raw:52} as never);const b=calendar(),headers=new Map(Array.from({length:8},(_,i)=>[i+1,new Set([51])]));expect(readLeagueCalendars(b,b.length,h,headers,identities(),[rule(67,0)],'2034-01-01')[0].status).toBe('unresolved');h.seasons=[];h.seasons.push({fixture_status:'confirmed',fixture_kind_raw:90,competition_id_raw:51} as never);expect(readLeagueCalendars(b,b.length,h,headers,identities(),[rule(67,0)],'2035-01-01')[0]).toMatchObject({status:'historical',reason:'same_save_calendar_and_history_completed'})})
})
describe('bounded binary readers',()=>{
  it('rejects truncated roots, unsupported types and oversized counts',()=>{const b=new Uint8Array(10);put(b,0,1);b.set([101,121,116,102,1,17],4);expect(readLeagueRule(b,67).errors).toBe(1);put(b,0,100001);expect(readLeagueRule(b,67).errors).toBe(1)})
  it('keeps contract registry framing experimental and rejects malformed tails',()=>{const b=new Uint8Array(80);put(b,20,1);put(b,25,123);put(b,29,440);expect(readContractRegistryDiagnostic(b)).toMatchObject({status:'experimental_local_shape',records:[{eid:123,field5:440,offset:24}]});b[79]=1;expect(readContractRegistryDiagnostic(b).status).toBe('unsupported');expect(readContractRegistryDiagnostic(new Uint8Array(9)).status).toBe('unsupported')})
})
